### ISSUE TITLE
[BUG] Blocks can be destroyed/moved in many ways

### ISSUE THREAD

**Issue by czm23333** [InlinedLambdas/AstralFlow#123]
A block can be destroyed/moved by player (BlockBreakEvent), fire (BlockBurnEvent), explosion (BlockExplodeEvent), fading (BlockFadeEvent), physics (BlockPhysicsEvent), decaying (LeavesDecayEvent) and piston (BlockPistonEvent).

To work perfectly, handle them all.

**Comment by iceBear67** [comment]
LeavesDecayEvent is called when leaves are decaying naturally but there're no natually leaves will be machines ( decorator blocks are not especially supported in this major version )

**Comment by iceBear67** [comment]
For blockPhysicsEvent: https://www.spigotmc.org/threads/know-if-blockphysicsevent-breaks-block.433541/

I've limited some exist APIs to using solid blocks instead of using non-solid blocks that requires this weird feature.

https://github.com/InlinedLambdas/AstralFlow/blob/c350a5e169cf61cad7b2f6ef97e1a62047fc7792/src/main/java/io/ib67/astralflow/api/item/machine/MachineItem.java#L64

I'll reconsider this when we introduce decorator supports

**Comment by czm23333** [comment]
> For blockPhysicsEvent: https://www.spigotmc.org/threads/know-if-blockphysicsevent-breaks-block.433541/
> 
> I've limited some exist APIs to using solid blocks instead of using non-solid blocks that requires this weird feature.
> 
> https://github.com/InlinedLambdas/AstralFlow/blob/c350a5e169cf61cad7b2f6ef97e1a62047fc7792/src/main/java/io/ib67/astralflow/api/item/machine/MachineItem.java#L64
> 
> I'll reconsider this when we introduce decorator supports

Even solid blocks can be moved. Have you ever thought of sand and gravel etc?

**Comment by iceBear67** [comment]
> > For blockPhysicsEvent: https://www.spigotmc.org/threads/know-if-blockphysicsevent-breaks-block.433541/
> > I've limited some exist APIs to using solid blocks instead of using non-solid blocks that requires this weird feature.
> > https://github.com/InlinedLambdas/AstralFlow/blob/c350a5e169cf61cad7b2f6ef97e1a62047fc7792/src/main/java/io/ib67/astralflow/api/item/machine/MachineItem.java#L64
> > 
> > I'll reconsider this when we introduce decorator supports
> 
> Even solid blocks can be moved. Have you ever thought of sand and gravel etc?

I'll ban them later. What does this project focus on is creating functionality blocks (i.e machines) and there're many choices excluding these special blocks.
