### ISSUE TITLE
[BUG] Cancelled events should be considered

### ISSUE THREAD

**Issue by czm23333** [InlinedLambdas/AstralFlow#126]
Obviously most events can be cancelled. But in listeners such as [BlockListener](https://github.com/InlinedLambdas/AstralFlow/blob/b2286cf152f9ab6cb431ef6f281fd19af12ff9cd/src/main/java/io/ib67/astralflow/internal/listener/BlockListener.java#L94) and the whole process, cancelled events are not handled correctly, which may lead to severe bugs.

**Comment by iceBear67** [comment]
I don't know what did you mean.Cancellation usually prevents the actual action from happening as the result and `@EventHandler` sets `ignoreCancelled` to true by default.

It seems no sense to handle more about cancelled events, such as machine termination, etc.

**Comment by czm23333** [comment]
> I don't know what did you mean.Cancellation usually prevents the actual action from happening as the result and `@EventHandler` sets `ignoreCancelled` to true by default.
> 
> It seems no sense to handle more about cancelled events, such as machine termination, etc.

But `@EventHandler` sets `ignoreCancelled` to false by default.

[javadoc is here](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/EventHandler.html)

You can see `Default: false`

**Comment by iceBear67** [comment]
Alright I remembered the wrong one
